ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="ApexTests"
ORG_URL="http://apextests.testing.lumosdao.io"
ORG_DESCRIPTION="testing"
ORG_LOGO="https://testing.lumosdao.io/.well-known/images/APTSGBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM=""
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""

[[CURRENCIES]]
code="APTS"
issuer="GBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36"
display_decimals=1
name="ApexTests"
desc="testing"
status="live"
image="https://testing.lumosdao.io/.well-known/images/APTSGBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36.png"