ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="Website Testing"
ORG_URL="http://websitetesting.testing.lumosdao.io"
ORG_DESCRIPTION="Testing website domain"
ORG_LOGO="https://testing.lumosdao.io/.well-known/images/BISAGBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM=""
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""

[[CURRENCIES]]
code="BISA"
issuer="GBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36"
display_decimals=1
name="Website Testing"
desc="Testing website domain"
status="live"
image="https://testing.lumosdao.io/.well-known/images/BISAGBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36.png"