ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="shikoku inu"
ORG_URL="http://shikokuinu60.lumosdao.io"
ORG_DESCRIPTION="LFG!"
ORG_LOGO="https://lumosdao.io/.well-known/images/2310GAJVTZUUUWGBMZR3B22Y6HLMLWJP4F6DYPLC5X2EQMOCW4J4LVCWKFBH.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM=""
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""

[[CURRENCIES]]
code="2310"
issuer="GAJVTZUUUWGBMZR3B22Y6HLMLWJP4F6DYPLC5X2EQMOCW4J4LVCWKFBH"
display_decimals=1
name="shikoku inu"
desc="LFG!"
status="live"
image="https://lumosdao.io/.well-known/images/2310GAJVTZUUUWGBMZR3B22Y6HLMLWJP4F6DYPLC5X2EQMOCW4J4LVCWKFBH.png"