ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="Wisdom"
ORG_URL="http://wisdom.lumosdao.io"
ORG_DESCRIPTION="Love is an addiction not attraction"
ORG_LOGO="https://lumosdao.io/.well-known/images/WSDMGBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM=""
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""

[[CURRENCIES]]
code="WSDM"
issuer="GBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36"
display_decimals=1
name="Wisdom"
desc="Love is an addiction not attraction"
status="live"
image="https://lumosdao.io/.well-known/images/WSDMGBPB22I6M3UHP3HZ475FTCIA5A7KVDJ6DMOCLTHX4KRRWMEHHUM7UY36.png"