ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="The Guudcian Method"
ORG_URL="http://theguudcianmethod.lumosdao.io"
ORG_DESCRIPTION="Love is an addiction not attraction"
ORG_LOGO="https://testing.lumosdao.io/.well-known/images/JHNSGBGF6Z33IHV5IJQMJELTK4O3RXOUHFMUTHQ2YGIGZNW5U3EQBBJHDRIX.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM=""
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""

[[CURRENCIES]]
code="JHNS"
issuer="GBGF6Z33IHV5IJQMJELTK4O3RXOUHFMUTHQ2YGIGZNW5U3EQBBJHDRIX"
display_decimals=1
name="The Guudcian Method"
desc="Love is an addiction not attraction"
status="live"
image="https://testing.lumosdao.io/.well-known/images/JHNSGBGF6Z33IHV5IJQMJELTK4O3RXOUHFMUTHQ2YGIGZNW5U3EQBBJHDRIX.png"