ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="Handshake"
ORG_URL="http://handshake.lumosdao.io"
ORG_DESCRIPTION="Handshake (SHAKE) - the friendliest meme token on the Soroban blockchain! Embrace the power of community and humor with every digital handshake."
ORG_LOGO="https://lumosdao.io/.well-known/images/SHAKEGAFQ37PYRWSRAMCG6YME2KC6RN3LC5IOYL25CF42CBXHUMEXXIWQSWQX.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM=""
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""

[[CURRENCIES]]
code="SHAKE"
issuer="GAFQ37PYRWSRAMCG6YME2KC6RN3LC5IOYL25CF42CBXHUMEXXIWQSWQX"
display_decimals=1
name="Handshake"
desc="Handshake (SHAKE) - the friendliest meme token on the Soroban blockchain! Embrace the power of community and humor with every digital handshake."
status="live"
image="https://lumosdao.io/.well-known/images/SHAKEGAFQ37PYRWSRAMCG6YME2KC6RN3LC5IOYL25CF42CBXHUMEXXIWQSWQX.png"