ACCOUNTS=[]

[DOCUMENTATION]
ORG_NAME="Lumos DAO"
ORG_URL="https://lumosdao.io"
ORG_DESCRIPTION="Lumos DAO Assets"
ORG_LOGO="https://lumosdao.io/public/images/logo.png"
ORG_TWITTER=""
ORG_INSTAGRAM=""
ORG_DISCORD=""
ORG_TELEGRAM="Telegramx'"
ORG_REDDIT=""
ORG_SUPPORT_EMAIL=""


[[CURRENCIES]]
code="nbhb"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/nbhbGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="nbgty"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="What is here"
status="live"
image="https://lumosdao.io/.well-known/images/nbgtyGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="nbgt"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="is working proprly"
status="live"
image="https://lumosdao.io/.well-known/images/nbgtGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="okl"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/oklGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="BUR"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Burger"
desc="jye[DATA]sp"
status="live"
image="https://lumosdao.io/.well-known/images/BURGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"

[[CURRENCIES]]
code="CAL"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Calculator"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/CALGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"

[[CURRENCIES]]
code="JNY"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="JES"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/JNYGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="DND"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="DND"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/DNDGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="JOP"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="JOP"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/JOPGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="PZZ"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Pizza"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/PZZGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"

[[CURRENCIES]]
code="CAP"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Capstan"
desc="jyesp"
status="live"
image="https://lumosdao.io/.well-known/images/CAPGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"



