ACCOUNTS=[""]

[DOCUMENTATION]
ORG_NAME="Lumos DAO"
ORG_URL="https://lumosdao.io"
ORG_DESCRIPTION="Lumos DAO Assets"
ORG_SUPPORT_EMAIL=""
ORG_LOGO="https://lumosdao.io/public/images/logo.png"



[[CURRENCIES]]
code="nbhb"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="yyu"
status="live"
image="https://lumosdao.io/.well-known/images/nbhbGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="nbgty"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="fgh"
status="live"
image="https://lumosdao.io/.well-known/images/nbgtyGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="nbgt"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="fgh"
status="live"
image="https://lumosdao.io/.well-known/images/nbgtGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="okl"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="yu"
desc="9000"
status="live"
image="https://lumosdao.io/.well-known/images/oklGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="BUR"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Burger"
desc="Burger (BUR) is the sizzling new meme token on the Soroban blockchain, serving up delicious gains and juicy community engagement. Don't miss out, or you might be left with an empty plate!"
status="live"
image="https://lumosdao.io/.well-known/images/BURGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"

[[CURRENCIES]]
code="CAL"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Calculator"
desc="Calculator (CAL) is the latest digital asset on the Soroban blockchain, adding up to be the next big thing in the crypto sphere. Crunch the numbers and get on board before the totals skyrocket!"
status="live"
image="https://lumosdao.io/.well-known/images/CALGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"

[[CURRENCIES]]
code="JNY"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="JES"
desc="What we have is an issue"
status="live"
image="https://lumosdao.io/.well-known/images/JNYGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="DND"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="DND"
desc="nothing"
status="live"
image="https://lumosdao.io/.well-known/images/DNDGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="JOP"
issuer="GCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH"
display_decimals=1
name="JOP"
desc="Just there"
status="live"
image="https://lumosdao.io/.well-known/images/JOPGCTDGADX3DTGM734T5WOCBDLXJH2KP7FCV2K5WCHQSPZ74SUDYAONTMH.png"

[[CURRENCIES]]
code="PZZ"
issuer="GBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS"
display_decimals=1
name="Pizza"
desc="Pizza (PIZZ) is the sizzling new meme token on the Soroban blockchain, serving up delicious gains and juicy community engagement. Don't miss out, or you might be left with an empty plate!"
status="live"
image="https://lumosdao.io/.well-known/images/PZZGBEE7ZVICFZCO6EGB4RTUBUIUJ4FKQOS7VGDJXGGNEUPD5O326OF6UOS.png"